# permissions for end users to edit jsonservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: jsonserver-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: json-server-operator
    app.kubernetes.io/part-of: json-server-operator
    app.kubernetes.io/managed-by: kustomize
  name: jsonserver-editor-role
rules:
- apiGroups:
  - example.com
  resources:
  - jsonservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com
  resources:
  - jsonservers/status
  verbs:
  - get
